### ISSUE TITLE
Add Blue Ocean support for artifact listing

### ISSUE THREAD

**Issue by samirageb** [jenkinsci/windows-azure-storage-plugin#101]
Presently Blue Ocean does not reflect artifacts uploaded via this plugin. There is an ongoing discussion around this behavior and the s3 plugin here: [https://issues.jenkins-ci.org/browse/JENKINS-48588](https://issues.jenkins-ci.org/browse/JENKINS-48588)

**Comment by gavinfish** [comment]
Hi @samirageb , sorry for the late reply.

This feature has been implemented in PR #106 , and will be available in the next release. Thanks for your suggestion.
