### ISSUE TITLE
Add a bit to the azure creditials plugin to allow this plugin to be easily managed via groovy.

### ISSUE THREAD

**Issue by kbfastcat** [jenkinsci/windows-azure-storage-plugin#108]
I'd love if someone could / would help me with a bit of code to make this easier to configure on container start, using groovy.

https://github.com/jenkinsci/azure-credentials-plugin - doesn't have native support for this. 

Any help here would be appreciated.

**Comment by kbfastcat** [comment]
for example, I'm not able to just do this, the imports aren't working in jenkins script console.
----
import jenkins.model.*
import hudson.security.*
import groovy.json.JsonSlurper
import hudson.model.*
import jenkins.model.*
import org.csanchez.jenkins.plugins.kubernetes.*
import org.csanchez.jenkins.plugins.kubernetes.volumes.*
import com.cloudbees.plugins.credentials.*
import com.cloudbees.plugins.credentials.common.*
import com.cloudbees.plugins.credentials.domains.*
import com.cloudbees.plugins.credentials.impl.*
import com.microsoft.azure.util.AzureCredentials
import com.microsoftopentechnologies.windowsazurestorage.*

stName = "test1";
stKey = "123";
stURL = "http://test1";

def azureCredential = new AzureCredentials.StorageAccountCredential(stName, stKey, stURL);

SystemCredentialsProvider.getInstance().getStore().addCredentials(Domain.global(), azureCredential)

**Comment by kbfastcat** [comment]
org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
Script1.groovy: 19: unable to resolve class AzureCredentials.StorageAccountCredential 
 @ line 19, column 23.
   def azureCredential = new AzureCredentials.StorageAccountCredential(stName, stKey, stURL);

**Comment by kbfastcat** [comment]
I think I'm close, but I don't write much groovy / java, can anyone solve this?

**Comment by gavinfish** [comment]
Hi @kbfastcat , I have made some changes, have a try, thanks.

```
import jenkins.model.*
import hudson.security.*
import groovy.json.JsonSlurper
import hudson.model.*
import jenkins.model.*
import org.csanchez.jenkins.plugins.kubernetes.*
import org.csanchez.jenkins.plugins.kubernetes.volumes.*
import com.cloudbees.plugins.credentials.*
import com.cloudbees.plugins.credentials.common.*
import com.cloudbees.plugins.credentials.domains.*
import com.cloudbees.plugins.credentials.impl.*
import com.microsoftopentechnologies.windowsazurestorage.helper.*

stName = "test1";
stKey = "123";
stURL = "http://test1";

def azureCredential = new AzureCredentials(CredentialsScope.SYSTEM, "id", "description", stName, stKey, stURL);

SystemCredentialsProvider.getInstance().getStore().addCredentials(Domain.global(), azureCredential)
```

**Comment by kbfastcat** [comment]
@gavinfish yes!! thanks! I owe you a starbucks coffee gift card ;)
