### ISSUE TITLE
excludeFilesPath should support multiple glob patterns

### ISSUE THREAD

**Issue by gabloe** [jenkinsci/windows-azure-storage-plugin#116]
It would be incredibly useful if we could exclude a list of glob patterns when uploading files to Azure storage.  For example, if I have files such as:

secrets.txt
forMyEyesOnly.json
...

I would like to exclude those 2 from the upload, but it's not intuitive to create a glob expression that would exclude them.  Can this support multiple patterns?

**Comment by gavinfish** [comment]
Sorry for the late response. It seems that you can use the `Optional list of artifacts to exclude from upload (Follows ant glob syntax)` part to do that in the advanced setting.

**Comment by gavinfish** [comment]
Closing it since no response for a long time. Feel free to reopen it.
