### ISSUE TITLE
upload artifacts that are not in job's workspace

### ISSUE THREAD

**Issue by jchauncey** [jenkinsci/windows-azure-storage-plugin#117]
I am working on a pipeline right now where the artifacts are not part of the normal build workspace `/var/lib/jenkins/workspaces/${JOB_NAME}`. Instead, they live at `/var/lib/jenkins/<some dir>/...`. I cant get the plugin to find any of the files that match my glob pattern. Is it possible that the plugin only looks for files that match within the workspace scope?

**Comment by ArieShout** [comment]
May be you can add a symbol link, or copy the artifacts to the workspace before the actual upload, with an extra `sh` command in the pipeline.

**Comment by gavinfish** [comment]
Hi @jchauncey , sorry for your inconvenience, indeed you can upload your files from anywhere with `dir` scope in your pipeline file. Sample:

```
dir('/var/lib/jenkins/<some dir>/...'){
    azureUpload  .....
}
```

**Comment by gavinfish** [comment]
Closing due to long time no response. Feel free to reopen it if still have problems
