### ISSUE TITLE
Support for `$web`

### ISSUE THREAD

**Issue by lucasmarcelli** [jenkinsci/windows-azure-storage-plugin#122]
I notice that you've added support for `$web` in dev, but it hasn't been released yet. Our deployment would benefit a _lot_ from this being released. Do you have a timeline?

**Comment by mikalai-okun** [comment]
I'm having exact issue with deploying my app.

**Comment by we-infra** [comment]
Yeah as of now, this is kinda *a must have feature*

**Comment by gavinfish** [comment]
This feature has been released in version 0.3.10, thanks for all your feedback!
