### ISSUE TITLE
Jenkins Azure Blob Storage plugin to copy the contents of Build folder and not build folder to $web azure blob static container

### ISSUE THREAD

**Issue by siddharthgrd** [jenkinsci/windows-azure-storage-plugin#124]
Hi Team,
We are using Jenkins Azure Blob plugin to deploy into Azure Blob Storage and have to use $web hosting feature in Azure.What happens is while mentioning the folder (list of artifacts to copy)like build/* , this is copying the entire build folder into $web container instead of only files inside the build folder. As per the Azure static web hosting, the document index file will be only pointed to index.html under $web i.e. $web/index.html, but in this case it is coming as $web/build/index.html which we don't want. This build folder can't be configure in the Azure Web static hosting(as build/index.html) and it has to be in the root as there are couple of files which comes as relative path automatically after build like /static/cs/ etc. https://azure.microsoft.com/en-us/blog/azure-storage-static-web-hosting-public-preview/ https://docs.microsoft.com/en-us/azure/storage/common/storage-java-jenkins-continuous-integration-solution

Please can someone check and respond as I need to copy the contents of build folder only..

Thanks

**Comment by gavinfish** [comment]
This plugin doesn't support your demand now. It will save the files with the same relative path as they are in the workspace. So is it possible to put your build/* files at the workspace root?

**Comment by siddharthgrd** [comment]
Hi Jie

The problem is in the workspace..it has source code, and generated node
modules folder post build along with build folder.So how can I copy? I
require the contents to be copied to Azure $web container root level for
static web hosting.

Thanks
Siddharth

On Tuesday, August 28, 2018, Jie Shen <notifications@github.com> wrote:
> This plugin doesn't support your demand now. It will save the files with
the same relative path as they are in the workspace. So is it possible to
put your build/* files at the workspace root?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci3.googleusercontent.com/proxy/iUMo4BUejlHlbWhRoz_dt9tedPIxWzf7d26pn0kfUppzgRyrpmejc-9tQ5cyYBGXsWuntuF7_BveOZvk3WzHXb9SwEFHO5hg3uoVcNKcyE37M8x_X6Eqh9ty7gGqll5pJFMIVYOE4-oj7Nwc7f6lvWsE_S9l2Q=s0-d-e1-ft#https://github.com/notifications/beacon/Aowca6ujfC8H10AmXqAe2luYDlX6Nicjks5uVN5igaJpZM4WNg-9.gif>

**Comment by gavinfish** [comment]
hi @siddharthgrd , do you use pipeline for your job, if so, you can use dir to choose which is your root upload space. For your case, below command should work.
```
dir('build') {
    azureUpload ......
}
```

**Comment by e-bits** [comment]
Hi,
I would really appreciate to get this upload to container root feature. 
In meantime I will try the pipeline approach from @gavinfish

**Comment by e-bits** [comment]
Hi @gavinfish,
your Pipeline approach is working perfectly fine. -> Many thanks for that hint.

Nevertheless, for me it would be nice to get an option whether to include the `<group-path>` or not.

**Comment by gavinfish** [comment]
Hi @e-bits ,
What do you mean by `get an option whether to include the <group-path> or not`? Can you be more specific?

**Comment by e-bits** [comment]
Hi @gavinfish ,
as I understand the final upload path will look like this: 
`http://<storage-account-name>.<azure-bob-service-endpoint>/<container-name>/<common-virtual-path>/<group-path>/<artifacts-file-name> `

My main goal would be to search artifachts like that `**/*.txt` and upload all matching files direclty into `<container-name>`. Currently this is not possible because of the following statement in documentation:
```
The final upload URL for each group of artifacts is constructed as follows, where <group-path> represents that last group URL path part: 
```

So for me a possible solution would be an option box in Advanced settings which is called something like `Upload to Container root` which will clean out the `<group-path>`.

Something like `<common-virtual-path>` which can be set in Advanced settings as well.

Please let me know if anything is still unclear.

Many Thanks for your help

**Comment by gavinfish** [comment]
Hi @e-bits ,
In which scenario will we need this feature? Is it a common one?

In my opinion, you can use command `cp **/*.txt tmp` to copy all your files into a temporary folder, and use this plugin to upload all the files to Azure storage.

**Comment by gavinfish** [comment]
Hi @e-bits ,
You are right, you can only use the temporary directory way in a pipeline project.
For a free project, there has not been a good way to solve it.
