### ISSUE TITLE
Inconsistiency in naming convention rules.

### ISSUE THREAD

**Issue by TomskiS** [jenkinsci/windows-azure-storage-plugin#125]
WAStoragePublisher uses local replaceMacro method with toLowerCase string modification, whereas AzureStorageBuilder uses similar macro from Utils (without toLowerCase  strategy).

Using container name with capital letters (e.g. PROJECT_NAME variable) storing finishes with success (replace to lower case) but download fails with same container name.

**Comment by gavinfish** [comment]
Fixed, will be available in next release.
