### ISSUE TITLE
Title for Azure Plugin entry at https://plugins.jenkins.io/windows-azure-storage should not be "Windows Azure"

### ISSUE THREAD

**Issue by bbenz** [jenkinsci/windows-azure-storage-plugin#127]
Need to change the plugin description at https://plugins.jenkins.io/windows-azure-storage to Azure storage or Microsoft Azure Storage, currently it's Windows Azure Storage.

**Comment by gavinfish** [comment]
@juniwang Is there any concern to make this change?

**Comment by gavinfish** [comment]
Moved to jira https://issues.jenkins-ci.org/browse/JENKINS-55635
