### ISSUE TITLE
blob endpoint url is changed after build

### ISSUE THREAD

**Issue by foreverfaint** [jenkinsci/windows-azure-storage-plugin#13]
i am using a special windows azure storage endpoint. i set the configuration like below:
- storage account name: portalvhdsxtpyty6dr213q
- storage account key: XXXXX
- blob service endpoint url: blob.core.chinacloudapi.cn
  then i click "validate storage credentials", it returns "Validation successful".

And then i add this plugin into post build action, the first build works very well. However the second build starts fail and reports: **Blob end point url --->http://portalvhdsxtpyty6dr213q.portalvhdsxtpyty6dr213q.blob.core.chinacloudapi.cn/<----**
you can see something wrong to add multiple "account name" to the final blob url. It seems this plugin generating a full blob url and saving it in every build without checking if the url was a full path.

**Comment by ramit-rulz** [comment]
I see the same issue. I am uploading to the same storage endpoint from multiple jobs and it looks like each job appends the storage account name to the url.

**Comment by chenkennt** [comment]
Closing old issues. Please reopen it if you still need this.
