### ISSUE TITLE
Randomly not uploading to blob

### ISSUE THREAD

**Issue by Guitrum** [jenkinsci/windows-azure-storage-plugin#130]
I have a Jenkins build that runs three azureUpload commands. They are all identical except for the storage accounts they are uploading to. Seemingly randomly, 2/3 of them will succeed, but one will not upload and I will get the following:

11:16:40 MicrosoftAzureStorage - Container name: spc-services-health
11:16:40 MicrosoftAzureStorage - share name: 
11:16:40 MicrosoftAzureStorage - File path: s03/87e02fa2.zip
11:16:40 MicrosoftAzureStorage - Virtual path: 77/
11:16:40 MicrosoftAzureStorage - Exclude path: 
11:16:40 MicrosoftAzureStorage - Uploading files to Microsoft Azure
11:16:40 MicrosoftAzureStorage - Need uploaded/archived file count = 1
11:16:44 MicrosoftAzureStorage - Uploaded/archived file count = 0

There is no error message and nothing in the storage account. Any tips?

**Comment by Guitrum** [comment]
gitHash = "${env.GIT_COMMIT}".substring(0,8)

// Zip artifacts
zip zipFile: "${SF_DEPLOY_CLUSTER}/${gitHash}.zip", archive: false, dir: "${WORKSPACE}/sfpkg/staging/${SF_DEPLOY_CLUSTER}"

// Upload artifacts to blob storage
azureUpload storageCredentialId: "blobcredID", storageType: 'blobstorage', containerName: "${CONTAINER_NAME}", filesPath: "${SF_DEPLOY_CLUSTER}/${gitHash}.zip", virtualPath: "${BUILD_NUMBER}"

**Comment by gavinfish** [comment]
I use a command `azureUpload storageCredentialId: "storage", storageType: 'blobstorage', containerName: "test", filesPath: "*.zip", virtualPath:"77"` and there is test.zip file at my workspace. Everything goes well. Anything special for your zip file then?

**Comment by Guitrum** [comment]
The only thing that would be special is that it is a pretty big zip file. I tried the process with a smaller zip file (3kb) and that worked flawlessly. But the one that is causing the intermittent issues is 60mb.

Is there a setting for a timeout or something that will ensure that a large file can be uploaded? maybe even a verbose setting to see what is happening?

**Comment by gavinfish** [comment]
Hi @Guitrum , I think there is a bug here and I will make a fix soon. But the new release cannot be available until 8, Oct because I am on vocation now. Sorry for your inconvenience.

**Comment by gavinfish** [comment]
Hi @Guitrum , I have tested your case with a zip file which is 80mb. But it works fine for me. Indeed the default uploading timeout is one day.

**Comment by gavinfish** [comment]
Closing for no response for a long time. Please feel free to reopen it if the issue still occurs.
