### ISSUE TITLE
Add option to strip parts of filesPath

### ISSUE THREAD

**Issue by 0x7f** [jenkinsci/windows-azure-storage-plugin#133]
On Jenkins I build a web application and the output files are in `./dist`. I want to upload them to a `$web` container. Everything works fine except that the upload path contains `dist/`. Is there a way to strip this part of the path? I thought about settings the current workdir to that dir, but the plugin code is explicitly making the path relative to the workspace dir. Also did not find any workaround using virtual path feature. Is it possible to strip paths and if not, can you please add the feature?

**Comment by gavinfish** [comment]
I think it is a duplicate of #124 .

**Comment by 0x7f** [comment]
Indeed it is. Did not find that ticket while searching through existing issues. Will close this one.
