### ISSUE TITLE
Downloading of artefacts from 0.3.5 broken after upgrade to 0.3.10

### ISSUE THREAD

**Issue by directhex** [jenkinsci/windows-azure-storage-plugin#134]
It appears `<storageType>` became a mandatory value for builds somewhere between 0.3.5 and 0.3.10. Clicking a link from an old build after upgrading the plugin throws an error:

```
    Error occurred while downloading artifact null
```

This means hundreds of thousands of builds now no longer have functional download capability.

After some investigation, we found that adding:

```
      <storageType>blobstorage</storageType>
```

inside the `<com.microsoftopentechnologies.windowsazurestorage.AzureBlobAction plugin="windows-azure-storage@0.3.5">` section of old build.xml files fixed downloadability - but this shouldn't be needed. A plugin update shouldn't break our existing builds.

**Comment by gavinfish** [comment]
@directhex , do you mean this upgrade would cause former builds' azure blobs links broken? If so, I will try to make a patch to fix this. I will try reproduce it on my side first. Thanks for your reporting!

**Comment by akoeplinger** [comment]
Correct.

I also just found out that even after adding the `<storageType>` entry to build.xml there's another case that's broken: when you use the "Download artifact from build" feature to download artifacts from a build which uploaded with v0.3.5 then no files will be found with the new version.

**Comment by gavinfish** [comment]
The cause of this issue is that when trying to download artifacts from build, plugin will deserialize from build related files which does not have the new variables like storageType. So it needs to inject the default value of blobs to fix it.

**Comment by akoeplinger** [comment]
@gavinfish thanks for fixing the issue! When do you plan to release a new version?

**Comment by gavinfish** [comment]
@akoeplinger , I think I could release it within this week.
