### ISSUE TITLE
Support cleaning virtual path instead of whole container

### ISSUE THREAD

**Issue by atrauzzi** [jenkinsci/windows-azure-storage-plugin#15]
Right now it looks like I have to clean the whole container if I want to wipe out the virtual path before uploading.

It would be nice if an option was added to allow for the removal of just everything within the path.  That way, if my build removes files, it won't orphan them.

**Comment by chenkennt** [comment]
Closing old issues. Please reopen it if you still need this.

**Comment by atrauzzi** [comment]
Uhh, this just gets assigned and then closed?  That's a weird process.
