### ISSUE TITLE
Add an option to not replicate full container path

### ISSUE THREAD

**Issue by atrauzzi** [jenkinsci/windows-azure-storage-plugin#16]
When I copy files from their full container path is preserved in my workspace.  This means that I have to nest downwards into directories I may not always know the name of in my dependent tasks.

It would be nice if the contents of the targeted directory could just be dumped to the root of the workspace instead of the full path to the directory itself.

**Comment by gavinfish** [comment]
hi @atrauzzi , sorry for the late reply.

I think your request has been realized in PR #9 `Allow flattening of download if desired.`.

Now you can set the advanced option `Flatten directories` when you download artifacts from Azure, and all your targeted files should be downloaded to a single directory, thanks.
