### ISSUE TITLE
Why does the publish step require build serialization

### ISSUE THREAD

**Issue by mmitche** [jenkinsci/windows-azure-storage-plugin#17]
Why does the publish step of the build require serialization with the previous build (at least if the container is not to be cleaned before uploading)?

From WAStoragePublisher.java

```
public BuildStepMonitor getRequiredMonitorService() {
    return BuildStepMonitor.STEP;
}
```

**Comment by chenkennt** [comment]
Close it as this one is over one year. Please feel free to reopen it if you have more info.
