### ISSUE TITLE
MicrosoftAzureStorage - Container name is missing or not valid

### ISSUE THREAD

**Issue by alex131290** [jenkinsci/windows-azure-storage-plugin#20]
I'm using this plugin in Jenkins, when i'n passig any environment variable (E.G ${JOB_NAME}) to the :"Container name" box and trying to upload, i'm getting an error: "MicrosoftAzureStorage - Container name is missing or not valid", i'm using the post build step "Upload artifacts to Microsoft Azure Blob storage".
If i'm providind a name to the "Container name" (E.G blob_test) and not an environment variable, it's working fine for me.

**Comment by abacaj** [comment]
Same issue here.

**Comment by directhex** [comment]
Does your job name contain characters such as `.`, or are your using a matrix job?

Only alphanumerics and `-` are valid in the container name. IMHO there should be a switch to auto-sanitise container names, for cases like this

**Comment by arroyc** [comment]
Try creating a container with the same {JOB_NAME} in azure portal.

**Comment by chenkennt** [comment]
Fixed.
