### ISSUE TITLE
[Request] Support of Content type when upload

### ISSUE THREAD

**Issue by tienlx93** [jenkinsci/windows-azure-storage-plugin#26]
In current plugin, every file uploaded to Blob is stored as application/octet-stream MIME type.
Do your plugin support different type of this. And if not, please help me where can I start from your project to support file types?
Thanks

**Comment by patope** [comment]
There is this #25 pull request for this.

**Comment by ArchangelSDY** [comment]
I'm closing this as it's implemented in #53 .
