### ISSUE TITLE
Jenkins unable to validate storage credentials

### ISSUE THREAD

**Issue by liaogz82** [jenkinsci/windows-azure-storage-plugin#30]
Hi, I am unable to get the plugin to validate storage credentials. I think it is because Jenkins is behind the firewall. I have already add in the firewall settings on the jenkins plugin page. How do I get it to work?

`Error : Failed to validate storage account details. Please verify storage account name and key. If you are using a private or other Windows Azure cloud service, make sure that the blob endpoint url is correct.`

**Comment by arroyc** [comment]
Just curious, if you have kept port 8080 open?

**Comment by liaogz82** [comment]
You mean Jenkins 8080? Of course!

**Comment by arroyc** [comment]
it's hard to reproduce .. because these are some spcial cases ... it would be great to have a live session/screen sharing .. it will help us to improve the product .. is that a possibility?

**Comment by liaogz82** [comment]
<img width="892" alt="screen shot 2016-12-14 at 2 08 50 pm" src="https://cloud.githubusercontent.com/assets/317035/21171375/c08330ee-c206-11e6-87aa-a32af593e7d6.png">

**Comment by arroyc** [comment]
try  with http://blob.core.windows.net/ in the blob service endpoint URL

**Comment by liaogz82** [comment]
<img width="891" alt="screen shot 2016-12-14 at 4 02 09 pm" src="https://cloud.githubusercontent.com/assets/317035/21174172/83a556f6-c216-11e6-89dc-c3b207c686a4.png">

doesn't seem to work. you can try using the key `G1Eu1BbxCamv/pmJBCk48cAdZaU1HguP5bSZ0+bDGmV3ggtmI1SzwF93TtEPX66OBQAWeOYrPOAHFUHyP0cNnw==`

**Comment by liaogz82** [comment]
session and screensharing is possible. My skype id is liaogz82. Please add me in

**Comment by arroyc** [comment]
![image](https://cloud.githubusercontent.com/assets/16231002/21174857/65ad269c-c194-11e6-8470-af65834699de.png)

**Comment by arroyc** [comment]
Follow jenkins wiki for setup instructions for proxy servers behind firewall
https://wiki.jenkins-ci.org/display/JENKINS/JenkinsBehindProxy

![image](https://cloud.githubusercontent.com/assets/16231002/21175343/a5ea299c-c196-11e6-82b2-31f2581714ac.png)

**Comment by liaogz82** [comment]
<img width="394" alt="screen shot 2016-12-15 at 2 47 17 pm" src="https://cloud.githubusercontent.com/assets/317035/21214481/e3d60420-c2d5-11e6-8461-9a6ebeb714a0.png">

 @arroyc my proxy settings has already been set up. So does that means I need to configure the JVM proxy setting too?

**Comment by liaogz82** [comment]
Ok it worked. I need to set it on the JVM level

`root@spdijenkinsq1:~# ps -ef | grep jenkins
jenkins   4550     1  0 15:05 ?        00:00:00 /lib/systemd/systemd --user
jenkins   4552  4550  0 15:05 ?        00:00:00 (sd-pam)
jenkins   4559     1  0 15:05 ?        00:00:00 /usr/bin/daemon --name=jenkins --inherit --env=JENKINS_HOME=/var/lib/jenkins --output=/var/log/jenkins/jenkins.log --pidfile=/var/run/jenkins/jenkins.pid -- /usr/bin/java -Djava.awt.headless=true -Dhttp.proxyHost=proxy.singaporepower.com.sg -Dhttp.proxyPort=8080 -Dhttps.proxyHost=proxy.singaporepower.com.sg -Dhttps.proxyPort=8080 -Dhttp.nonProxyHosts=*.in.spdigital.io -jar /usr/share/jenkins/jenkins.war --webroot=/var/cache/jenkins/war --httpPort=8080 --httpsPort=8443 --httpsKeyStore=/var/lib/jenkins/key/keystore.jks --httpsKeyStorePassword=password
jenkins   4560  4559 99 15:05 ?        00:00:07 /usr/bin/java -Djava.awt.headless=true -Dhttp.proxyHost=proxy.singaporepower.com.sg -Dhttp.proxyPort=8080 -Dhttps.proxyHost=proxy.singaporepower.com.sg -Dhttps.proxyPort=8080 -Dhttp.nonProxyHosts=*.in.spdigital.io -jar /usr/share/jenkins/jenkins.war --webroot=/var/cache/jenkins/war --httpPort=8080 --httpsPort=8443 --httpsKeyStore=/var/lib/jenkins/key/keystore.jks --httpsKeyStorePassword=password`

**Comment by liaogz82** [comment]
This plugin should look into using the proxy settings from jenkins instead from the JVM
