### ISSUE TITLE
[Request] Plugin should not use proxy settings from JVM. They should take it from Jenkins

### ISSUE THREAD

**Issue by liaogz82** [jenkinsci/windows-azure-storage-plugin#31]
I can only run the plugin properly when I set the proxy setting on JVM which is not right. There are several Jenkins plugin that are already taking the proxy settings from Jenkins. One of them is Github Jenkins plugin. 

[git-plugin](https://github.com/jenkinsci/git-plugin/blob/e3b32afe0697ec2825fb86b82417f311874cecc5/src/main/java/hudson/plugins/git/RemoteConfigConverter.java)

Please look into implementing this feature so that users do not need to add in any Java arguments

**Comment by arroyc** [comment]
there is some work going on that ... https://github.com/jenkinsci/windows-azure-storage-plugin/pull/19
We are reviewing and testing it .. once done .. you will get this new feature

**Comment by gavinfish** [comment]
Hi @liaogz82 , sorry for the late reply.

This request has been implemented in PR #107 , and will be released soon. Thanks for your suggestion.
