### ISSUE TITLE
Upload to the correct azure folder path, not follow jenkins workspace path

### ISSUE THREAD

**Issue by liaogz82** [jenkinsci/windows-azure-storage-plugin#33]
I have a jenkins android build, which after building the app the apk file is placed at `app/build/outputs/apk/SP*.apk`. That file path is placed on the `List of artifacts to upload` field.

But when uploading it to azure storage, it create the same `app/build/outputs/apk/SP*.apk` path in the container. I just want the apk to store on the root level in the container itself. Is that possible?

**Comment by arroyc** [comment]
@liaogz82  .. can you share a sample screenshot? Also which build are you using?

**Comment by liaogz82** [comment]
<img width="343" alt="screen shot 2016-12-28 at 1 10 38 pm" src="https://cloud.githubusercontent.com/assets/317035/21514360/3d24f300-ccff-11e6-8d58-e693fd567426.png">

I hope this screenshot is sufficient. I want it to be on jarvis root folderm but it ended up taking the full path from the jenkins workspace

**Comment by liaogz82** [comment]
![screen shot 2016-12-28 at 1 17 18 pm](https://cloud.githubusercontent.com/assets/317035/21514424/f0a56e6e-ccff-11e6-89b1-37634b580018.png)

This is my jenkins post build action setting to upload the final apk file up to blob storage

**Comment by arroyc** [comment]
@liaogz82  ... there is a plan to change the current user experience ... we are thinking to introduce 
source/browse and destination separately,  stay tuned ...

**Comment by arroyc** [comment]
@liaogz82  .. thats a good suggestion but if you want your file to be on root folder, you have to copy the files to your local machine accordingly. This is the standard ant way of doing. At this moment there is no plan to change it.
