### ISSUE TITLE
v0.3.3 : Global credentials are lost

### ISSUE THREAD

**Issue by kev-in-shu** [jenkinsci/windows-azure-storage-plugin#43]
Since version 0.3.3, it is impossible to save the credentials for Microsoft Azure Storage.

Everytime we click on save and come back to the editing screen, the credentials are reset as follows : 

* Storage Account Name : empty
* Storage Account Key : empty	
* Blob EndPoint URL : http://blob.core.windows.net/

**Comment by clguimanMSFT** [comment]
@kev-in-shu please include a screenshot and the logs

**Comment by kev-in-shu** [comment]
![screenshot](https://cloud.githubusercontent.com/assets/7252851/23698864/73c301f2-03ed-11e7-8887-be59af55ae17.gif)

[bug report logs.zip](https://github.com/jenkinsci/windows-azure-storage-plugin/files/827213/bug.report.logs.zip)

**Comment by clguimanMSFT** [comment]
The credentials are not lost, you can use them, just that you don't see them when updating. I will fix that
