### ISSUE TITLE
windows-azure-storage-plugin is keeping my files locked.

### ISSUE THREAD

**Issue by micheltol** [jenkinsci/windows-azure-storage-plugin#49]
Hi,

first of all thanks for this amazing plugin. It's a core component of our deployment pipeline. 
Lately I am having some issues after uploading my artifacts.

I upload my deliverable (zip file +/- 140MB) via the windows-azure-storage-plugin.
After the upload succeeds the file stays locked and I am unable to clean up the workspace.
Waiting for 30 minutes does not help.
Environment: 
OS:Windows  2012R2
Jenkins: 2.5.2
windows-azure-storage-plugin 0.3.2 (same issue with 0.3.4)
Process Explorer (SysInternals) is showing the java.exe is keeping the file locked.

When I remove the windows-azure-storage-plugin from my build, the workspace gets cleaned up.
Any tips, hints  how I could resolve this?

Log file:
C:\Program Files (x86)\Jenkins\Build Test42Server  - Package Artifacts>exit 0 
MicrosoftAzureStorage - Uploading files to Microsoft Azure
Uploaded blob with uri http://XXXXXX.blob.core.windows.net/jenkins/test-42server/797.zip in 00:00:07.808 (HH:mm:ss.S)
MicrosoftAzureStorage - Uploaded/archived file count = 1 
[WS-CLEANUP] Deleting project workspace...Cannot delete workspace :Unable to delete 'C:\Program Files (x86)\Jenkins\Build Test42Server  - Package Artifacts'. Tried 3 times (of a maximum of 3) waiting 0.1 sec between attempts.
ERROR: Step ‘Delete workspace when build is done’ failed: Cannot delete workspace: Unable to delete 'C:\Program Files (x86)\Jenkins\Build Test42Server  - Package Artifacts'. Tried 3 times (of a maximum of 3) waiting 0.1 sec between attempts.

**Comment by clguimanMSFT** [comment]
Looked around the code and found a possible issue. I wrote a fix(#50), but I need you to  verify it
Please install the plugin from here (or build it yourself from my fork, branch 'fix-lock') : http://devopspublicstorage.blob.core.windows.net/devops-jenkins/windows-azure-storage/clguimanMSFT/file-lock/1/windows-azure-storage.hpi

**Comment by micheltol** [comment]
I just left the office; will check tomorrow. Thanks for the quick response!

**Comment by micheltol** [comment]
Hi, just tested it. It works for me! Thanks for the fix!
