### ISSUE TITLE
Blob service endpoint URL

### ISSUE THREAD

**Issue by spawluk** [jenkinsci/windows-azure-storage-plugin#5]
Using version 0.3.0, and promotion plugin, upload artefact to Azure causes that endpoint URL is prefixed by Storage account name. F.e.:

after second build service URL will be: https://[accountName].[accountName].blob.core.windows.net/

**Comment by lonelysh** [comment]
Use http instead of https for blob.core.windows.net could solve this issue, and the default url starts with http.   But other endpoint is still not working, whatever http or https. 

Glad to see the updates, and wait for available update.
