### ISSUE TITLE
Content Type auto detecting should be disabled by default

### ISSUE THREAD

**Issue by clguimanMSFT** [jenkinsci/windows-azure-storage-plugin#63]
The content type auto detection is enabled by default, that means old jobs will change behavior all of a sudden. That shouldn't happen, users should opt in for new features.
I noticed this problem when the job that was uploading hpi files started uploading them with the zip content type.

**Comment by ArchangelSDY** [comment]
For old jobs the auto detection config is missing, the value will be false by default. I tested both the traditional freestyle job and pipeline job and seems cannot reproduce the problem:

# Freestyle job
1. Create a freestyle job. The config will persist like:
```xml
  <publishers>
    <com.microsoftopentechnologies.windowsazurestorage.WAStoragePublisher plugin="windows-azure-storage@0.3.5">
      <containerName>jenkins-dev</containerName>
      <cntPubAccess>false</cntPubAccess>
      <cleanUpContainer>false</cleanUpContainer>
      <allowAnonymousAccess>false</allowAnonymousAccess>
      <uploadArtifactsOnlyIfSuccessful>false</uploadArtifactsOnlyIfSuccessful>
      <doNotFailIfArchivingReturnsNothing>false</doNotFailIfArchivingReturnsNothing>
      <uploadZips>false</uploadZips>
      <doNotUploadIndividualFiles>false</doNotUploadIndividualFiles>
      <filesPath>*.hpi</filesPath>
      <excludeFilesPath></excludeFilesPath>
      <virtualPath></virtualPath>
      <doNotWaitForPreviousBuild>false</doNotWaitForPreviousBuild>
      <storageCredentialId>b5f30ec1-4cb6-41a5-be56-f09c3f09598e</storageCredentialId>
    </com.microsoftopentechnologies.windowsazurestorage.WAStoragePublisher>
  </publishers>
```
2. Upgrade the plugin.
3. Run the job.
4. Upload successfully. The content type is application/octet-stream.

# Pipeline job
1. Create a pipeline job with following script:
```groovy
    stage('upload') {
        step([$class: 'WAStoragePublisher', containerName: 'jenkins-dev', filesPath: '*.hpi', storageCredentialId: 'b5f30ec1-4cb6-41a5-be56-f09c3f09598e', excludeFilesPath: '', virtualPath: ''])
    }
```
2. Upgrade the plugin.
3. Run the job.
4. Upload successfully. The content type is application/octet-stream.

Could you provide more details about the steps to reproduce the problem?

**Comment by clguimanMSFT** [comment]
It seems the issue is in Microsoft Edge, If I open the URL in Edge it will detect the hpi as zip. Works fin in Chrome.
Sorry for the false issue :)
I'll close it
