### ISSUE TITLE
Support secure (https) upload and download

### ISSUE THREAD

**Issue by moshezvi** [jenkinsci/windows-azure-storage-plugin#68]
When a storage account is configure with the **Secure transfer required** option enabled, the plugin fails to upload files, since it only uploads over http.
Furthermore, even if the endpoint url is configured with https, it is ignored: the actual upload is performed over http. 
This is a security concern, primarily because it also brings into question the matter of credentials passing over an insecure connection.

**Comment by moshezvi** [comment]
@ArchangelSDY - thanks so much! do you have any idea when this will be released as part of an official build?

**Comment by ArchangelSDY** [comment]
@chenkennt When will be our next release?

**Comment by chenkennt** [comment]
Should be in one or two weeks.

**Comment by nmardiks** [comment]
@chenkennt any update on the next release? We would also want to use the plugin and this is a blocker for us. Thanks!
