### ISSUE TITLE
Blob Metadata 

### ISSUE THREAD

**Issue by wabuhigleh** [jenkinsci/windows-azure-storage-plugin#8]
Is it possible to implement blob metadata to the uploaded file?
I saw that option in azure cross-platform command line client, but it will be great if such option is available in this Jenkins plugin:

azure storage blob upload <arguments ... > -m "key1=value1;key2=value2; ..."

**Comment by wabuhigleh** [comment]
I have implemented this feature and tested it locally.
I can create a pull request for review .. it will be great if you can incorporate this change into the plugin.

Regards,
Waddah

**Comment by AnneTheAgile** [comment]
@wabuhigleh , did you submit a PR?

**Comment by ArchangelSDY** [comment]
I'm closing this as it's implemented in #54 .
