### ISSUE TITLE
Authenticate failure over HTTPS

### ISSUE THREAD

**Issue by samirageb** [jenkinsci/windows-azure-storage-plugin#80]
When the 'secure transfer required' option is set on a storage account, the plugin will not succesfully authenticate. Obviously this forces storage accounts using this plugin to be 'opt-in' for HTTPS. This is an unfortunate limitation and should be rectified ASAP to support security best practices. Also, this condition should be added to the documentation as a 'known issue'.

Plugin version: 0.3.6
Jenkins version: 2.8.5

**Comment by juniwang** [comment]
Duplicate with https://github.com/jenkinsci/windows-azure-storage-plugin/issues/68. It's already fixed and will be released soon.

**Comment by juniwang** [comment]
Fixed in version 0.3.7: https://plugins.jenkins.io/windows-azure-storage
