### ISSUE TITLE
Unable to hide/ clear logs when uploading and downloading artifacts to and from Azure

### ISSUE THREAD

**Issue by ngeegoh** [jenkinsci/windows-azure-storage-plugin#83]
I think it should be great if we have an option to hide the logs when downloading and uploading from and to Azure, as it will keep the build console clean and easy to see what happen during the build rather than being annoyed by heaps of Azure logs if there are a lot of artifacts required for the build which makes it really difficult to diagnose the issue at first.

**Comment by chenkennt** [comment]
There is value to display all logs, which is helpful in troubleshooting.
