### ISSUE TITLE
Failed to download the artifacts from "Azure Artifacts" link in Jenkins 

### ISSUE THREAD

**Issue by ngeegoh** [jenkinsci/windows-azure-storage-plugin#84]
In the build job, there is a link "Azure Artifacts" on the left side of the job page which points to a broken link. Instead of pointing to the azure URL and download the artifacts from Jenkins, it tries to look for server's local path and throws the HTTP ERROR 500. The Azure artifacts should be able to be downloaded from that link in Jenkins instead of only be downloaded from the Azure Storage Account (Azure portal) since some people do not have access to Azure. 

`HTTP ERROR 500

Problem accessing /job/builds/view/dev/job/--/--/Azure/processDownloadRequest/--/--/packages.7z. Reason:

    Error occurred while downloading artifact The server encountered an unknown failure: `

**Comment by juniwang** [comment]
Fixed in 0.3.8
