### ISSUE TITLE
Blank window when trying to configure 

### ISSUE THREAD

**Issue by kristine-sl** [jenkinsci/windows-azure-storage-plugin#85]
Hello, 

I am trying to configure my storage account in Jenkins, but when I try to add storage account under "Configure System", I only get a blank window and am not able to configure the service. 

I updated all my plugins before doing this, so I am using version 0.3.7 of the plugin.

![jenkins-bug](https://user-images.githubusercontent.com/3509839/33545246-c5ee8d50-d8dd-11e7-82a5-3d2b483f022e.png)

**Comment by juniwang** [comment]
Which version of Jenkins are you using?

**Comment by kristine-sl** [comment]
I'm currently using Jenkins ver. 2.73.3

**Comment by juniwang** [comment]
Tried both on Azure and my local PC, cannot reproduce the issue. Is there any logs in Jenkins?

**Comment by MikeWasson** [comment]
Same issue with 0.3.7 of the plugin, using Jenkins v 2.89.2 from the Azure marketplace.

**Comment by lbrader** [comment]
Same issue with 0.3.7 version of the plug and Jenkins version 2.89.2 from Azure Marketplace

**Comment by juniwang** [comment]
Fixed in 0.3.8
