### ISSUE TITLE
[Request] Copy full folders

### ISSUE THREAD

**Issue by jakubmichalec** [jenkinsci/windows-azure-storage-plugin#86]
Is it possible to copy full folders rather than each file? 

In my artifacts I have a lot of small files, plugin copy one by one and it's take 'forever'. I want to copy all stuff from azure container, atm with AzCopy it's take ~2 min, with plugin almost 30 min

**Comment by juniwang** [comment]
We rely on the Azure Java SDK. That means we have no other option but copy file one by one. Not sure what's inside the AzCopy, but I guess it handle files one by one as well with some kind of performance optimization.

There is a [Storage Data movment](https://github.com/Azure/azure-storage-net-data-movement) Nuget package which should be much better than the early versions.  Unfortunately no corresponding Java version for now.

**Comment by gavinfish** [comment]
Hi @jakubmichalec , sorry for the late reply.

To make downloading process faster, I have made a few changes in PR #102 which would mitigate your problem. And this feature will be available in next release. Thanks for your suggestion.
