### ISSUE TITLE
Content type detection with js files sometimes uses "text/html"

### ISSUE THREAD

**Issue by degoltz** [jenkinsci/windows-azure-storage-plugin#89]
There is a known [bug](https://issues.apache.org/jira/browse/TIKA-1141) in Tika regarding some js files content type detection:
> The Mimetypes detector will return text/html as the mimetype for any javascript file that contains the string "<html" in it. I believe this is due to the rule <match value="<html" type="string" offset="0:8192"/> in the tika-mimetypes.xml file.

This was not fixed in Tika for a few years now and is causing some of our JS files to upload with HTML content type (for example jQuery).

When I upload the same file directly to the blob storage in the Azure portal, I don't need to select a content type and it get's a correct content type (text/javascript).
We tried removing the checkbox for "Auto detect content type" and that made all file upload with "application/octet-stream" and not have their content type set by Azure.
We can't set a static content type as we upload many files of many types in a single build.

We have 4 optional solutions:

1. Replace Tika with a different library that can identify JS files correctly.
2. Add a workaround like [here](https://jira.sakaiproject.org/browse/KNL-1306) and make sure that js file, in particular, get the correct content type.
3. Allow Azure to select the correct content type when no content type was set.
4. Allow us to provide a "Content-type override dictionary" that will resolve an extension to a content type without using Tika for those types. we will send something like:
`{ "js":"application/javascript" }`

**Comment by degoltz** [comment]
We had a discussion in [TIKA-1141](https://issues.apache.org/jira/browse/TIKA-1141).
They think the code might not send the "real" filename to tika and so this fails

**Comment by juniwang** [comment]
Debugged locally just a moment ago, with all default settings to upload js files to azure blob storage(leave content type blank, check the auto-detect checkbox), it seems to me from both the debug window and azure storage explorer, the content type is correctly set to `application/javascript`.  Both Tika 1.14 and 1.17 worked(with the real name).  

The [repo](https://github.com/juniwang/open-hackathon/tree/master/open-hackathon-client/src/client/static/js/jquery) for test which includes the same version of jQuery as yours.  Are there any other differences?

**Comment by degoltz** [comment]
Thanks @juniwang
