### ISSUE TITLE
unable to connect from behind HTTP_PROXY

### ISSUE THREAD

**Issue by seanshankus** [jenkinsci/windows-azure-storage-plugin#98]
I'm having issues where I cannot configure this plugin to any Azure Storage.  I *think* its because i'm behind a HTTP_PROXY but i'm not sure how to confirm this or configure it (my apologies if this is not the correct place for this request).  Given that there are only a few entries to put in the global configuration (Storage Account Name, Storage Account Key, BLOB Endpoint URL, ID) i'm not sure how i can mess this part up.  Key1 vs Key2 seems to be the "trickest" part to make sure that the blob is looking at the right key, but to be safe i've tried both to no amend.  Which is why I think its the plugin/jenkins not authenticating to the HTTP_PROXY correctly.  The error message on the Jenkins credential screen (no matter what I put in for values) is: "Failed to validate storage account details. Please verify storage account name and key. If you are using a private or other Windows Azure cloud service, make sure that the blob endpoint url is correct."

Screen shots:
![azure](https://user-images.githubusercontent.com/13694916/37001773-9adf833a-2095-11e8-9edd-1c9a94fcd004.PNG)
![jenkins](https://user-images.githubusercontent.com/13694916/37001774-9af4888e-2095-11e8-9ef1-3054a28edf99.PNG)

**Comment by gavinfish** [comment]
hi @seanshankus , could you please let me how you set HTTP_PROXY, so that I can reproduce the situation. By the way, there are two keys because `you can maintain connections using one key while regenerating the other`. You can use either of the keys in the configuration.

**Comment by gavinfish** [comment]
Jenkins proxy setting is effective in this plugin since version 0.3.9.

Closing for no response for a long time. You are free to reopen this issue if you still have related problems, thanks.
